# Generated by Django 4.2.9 on 2024-07-20 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='address',
            field=models.TextField(default='default'),
        ),
        migrations.AddField(
            model_name='account',
            name='phone_number',
            field=models.CharField(default='default', max_length=15),
        ),
    ]
