# Generated by Django 4.2.9 on 2024-07-03 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='user',
        ),
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(default='default', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='client',
            name='first_name',
            field=models.CharField(default='default', max_length=30),
        ),
        migrations.AddField(
            model_name='client',
            name='last_name',
            field=models.CharField(default='default', max_length=30),
        ),
    ]
