# Generated by Django 4.2.9 on 2024-07-03 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_client_user_client_email_client_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coiffeur',
            name='user',
        ),
        migrations.AddField(
            model_name='coiffeur',
            name='address',
            field=models.TextField(default='default'),
        ),
        migrations.AddField(
            model_name='coiffeur',
            name='email',
            field=models.EmailField(default='default', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='coiffeur',
            name='first_name',
            field=models.CharField(default='default', max_length=30),
        ),
        migrations.AddField(
            model_name='coiffeur',
            name='last_name',
            field=models.CharField(default='default', max_length=30),
        ),
        migrations.AddField(
            model_name='coiffeur',
            name='phone_number',
            field=models.CharField(default='default', max_length=15),
        ),
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.TextField(default='default'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
