# Generated by Django 4.2.9 on 2024-07-03 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_coiffeur_user_coiffeur_address_coiffeur_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='client',
        ),
        migrations.AddField(
            model_name='appointment',
            name='client_first_name',
            field=models.CharField(default='default', max_length=30),
        ),
        migrations.AddField(
            model_name='appointment',
            name='client_last_name',
            field=models.CharField(default='default', max_length=30),
        ),
    ]
