# Generated by Django 4.2.9 on 2024-07-10 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_appointment_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='phone_number',
        ),
    ]
