# Generated by Django 4.2.9 on 2024-07-19 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_alter_appointment_options_alter_appointment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='service',
        ),
        migrations.AddField(
            model_name='appointment',
            name='service',
            field=models.ManyToManyField(related_name='appointments', to='dashboard.service'),
        ),
    ]
